use std::fs;
use std::path::Path;

fn main() {
    // Walk the backend directory and generate embedded file entries
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let generated = Path::new(&out_dir).join("backend_files.rs");

    let mut entries = Vec::new();
    collect_entries(&Path::new("backend"), "", &mut entries);

    let mut code =
        "// Auto-generated by build.rs — embeds backend files into the binary\n".to_string();
    code.push_str("pub const BACKEND_FILES: &[(&str, &[u8])] = &[\n");
    for (relative_path, abs_path) in &entries {
        // Use include_bytes! so the compiler embeds the file content
        let abs_path_escaped = abs_path.replace('\\', "\\\\");
        code.push_str(&format!(
            "    (\"{}\", include_bytes!(\"{}\")),\n",
            relative_path, abs_path_escaped
        ));
    }
    code.push_str("];\n");

    fs::write(&generated, &code).unwrap();
    println!("cargo:rerun-if-changed=backend/");

    tauri_build::build();
}

fn collect_entries(dir: &Path, prefix: &str, entries: &mut Vec<(String, String)>) {
    if !dir.exists() {
        return;
    }
    for entry in fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();

        if name == "__pycache__" || name.ends_with(".pyc") {
            continue;
        }

        let relative = if prefix.is_empty() {
            name.clone()
        } else {
            format!("{}/{}", prefix, name)
        };

        if path.is_dir() {
            collect_entries(&path, &relative, entries);
        } else {
            let abs = fs::canonicalize(&path).unwrap();
            entries.push((relative, abs.to_string_lossy().to_string()));
        }
    }
}
